# Generated by Django 4.1 on 2022-08-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default='', on_delete=models.SET(''), to='news.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
